# Generated by Django 4.2.25 on 2025-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
